name = "SFTP"
uuid = "fba9f14e-740f-4152-9d1a-f26f0fc12be4"
authors = ["Peter Bräuer <pb866.git@gmail.com> and contributors"]
version = "0.2.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
